apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: webserver
  namespace: swaptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: gcr.io/yescloud/github.com/yes-soft-de/swap-time
          imagePullPolicy: Always
          name: php-apache
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/upload/image
              name: pvc-sym-m
            - mountPath: /home
              name: pvc-sym-e              
      volumes:
        - name: pvc-sym-m
          persistentVolumeClaim:
            claimName: pvc-sym-uploud
        - name: pvc-sym-e
          persistentVolumeClaim:
            claimName: pvc-sym-e   
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    run: web-service
  name: web-service
  namespace: swaptime
spec:
  clusterIP: 10.4.5.143
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32140
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apache
  sessionAffinity: None
  type: LoadBalancer
